name: Windows
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout ffmpeg
        uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: n4.4.4
          path: ffmpeg
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup MYSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          msystem: UCRT64
          install: >-
            make
            yasm
      - name: Build ffmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          chmod +x ./configure
          ./configure --disable-debug --enable-asm --enable-yasm --target-os=win64 --arch=x86_64 --toolchain=msvc --enable-small --disable-programs --disable-doc --disable-avdevice  --disable-swscale --disable-postproc --disable-avfilter --disable-avformat --enable-shared --disable-muxers --prefix=./install
          make -j2
          make install

      