name: Windows
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout ffmpeg
        uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: n5.1.3
          path: ffmpeg
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup MYSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          msystem: UCRT64
          install: >-
            make
            yasm
      - name: Build ffmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          chmod +x ./configure
          ./configure --prefix=./install --enable-shared --disable-debug --disable-protocols --enable-asm --enable-yasm --target-os=win64 --arch=x86_64 --toolchain=msvc --disable-gpl --disable-programs --disable-doc --disable-avdevice --disable-swresample  --disable-swscale --disable-postproc --disable-avfilter --disable-filters --disable-devices --disable-demuxers --disable-muxers --disable-avformat
          make -j2
          make install
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./ffmpeg/install/*,./Release.txt -DestinationPath ffmpeg.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ffmpeg.zip

      